### PR TITLE
Precompile CS to JS and remove production dependency on coffee-script.

### PR DESCRIPTION
**Pull request by tamlyn**
I'm using Babel with source maps and found that this module's use of the coffee-script require hook was breaking my source mapping leading to incorrect stack traces in my tests. I believe precompiling to JS is the [recommended practice](http://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript) for modules written in CoffeeScript but I'm no expert. I've tested this change locally but haven't tested publishing it to npm.

### CODE REVIEW

**Comment by gtramontina** [comment]
Makes total sense! Thanks for contributing!

**Comment by gtramontina** [comment]
Published [1.1.0](https://www.npmjs.com/package/passport-stub)!
Let me know if you find anything weird! :beers:

**Comment by ctide** [comment]
I don't think this worked. Installing passpost-stub into a project that doesn't use coffeescript doesn't actually compile it (and doesn't allow it to be required in.)

The end result of the installed package looks like:

/development/galvanize/workbook/node_modules/passport-stub (master ✘)✹ ᐅ find .
.
./.editorconfig
./.npmignore
./package.json
./README.md
./src
./src/passport-stub.coffee

No .js files are actually built during the npm install process.

**Comment by tamlyn** [comment]
Dang! I accidentally added `lib/` to `.npmignore` instead of `src/`. PR incoming...

**Comment by tamlyn** [comment]
Actually I wasn't being a complete idiot, see #16.

**Comment by gtramontina** [comment]
Oh true! I knew it and it totally slipped through my fingers! :stuck_out_tongue: ... Checking it out now...

**Pull request merged**
